/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Contact {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "organizationId", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<uuid::Uuid>,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Box<models::RolesDetails>>,
    #[serde(rename = "company", skip_serializing_if = "Option::is_none")]
    pub company: Option<Box<models::CompanyDetails>>,
    #[serde(rename = "person", skip_serializing_if = "Option::is_none")]
    pub person: Option<Box<models::PersonDetails>>,
    #[serde(rename = "addresses", skip_serializing_if = "Option::is_none")]
    pub addresses: Option<Box<models::ContactAddresses>>,
    #[serde(rename = "xRechnung", skip_serializing_if = "Option::is_none")]
    pub x_rechnung: Option<Box<models::XRechnung>>,
    #[serde(rename = "emailAddresses", skip_serializing_if = "Option::is_none")]
    pub email_addresses: Option<Box<models::ContactEmailAddresses>>,
    #[serde(rename = "phoneNumbers", skip_serializing_if = "Option::is_none")]
    pub phone_numbers: Option<Box<models::ContactEmailAddresses>>,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(rename = "archived")]
    pub archived: bool,
}

impl Contact {
    pub fn new(id: uuid::Uuid, version: i32, archived: bool) -> Contact {
        Contact {
            id,
            organization_id: None,
            version,
            roles: None,
            company: None,
            person: None,
            addresses: None,
            x_rechnung: None,
            email_addresses: None,
            phone_numbers: None,
            note: None,
            archived,
        }
    }
}

