/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceXRechnung {
    #[serde(rename = "buyerReference", skip_serializing_if = "Option::is_none")]
    pub buyer_reference: Option<String>,
}

impl InvoiceXRechnung {
    pub fn new() -> InvoiceXRechnung {
        InvoiceXRechnung {
            buyer_reference: None,
        }
    }
}

