/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentConditionsPaymentDiscountConditions {
    #[serde(rename = "discountPercentage", skip_serializing_if = "Option::is_none")]
    pub discount_percentage: Option<f64>,
    #[serde(rename = "discountRange", skip_serializing_if = "Option::is_none")]
    pub discount_range: Option<i32>,
}

impl PaymentConditionsPaymentDiscountConditions {
    pub fn new() -> PaymentConditionsPaymentDiscountConditions {
        PaymentConditionsPaymentDiscountConditions {
            discount_percentage: None,
            discount_range: None,
        }
    }
}

