/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentItem {
    #[serde(rename = "paymentItemType")]
    pub payment_item_type: PaymentItemType,
    #[serde(rename = "postingDate")]
    pub posting_date: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "currency")]
    pub currency: Currency,
}

impl PaymentItem {
    pub fn new(payment_item_type: PaymentItemType, posting_date: String, amount: f64, currency: Currency) -> PaymentItem {
        PaymentItem {
            payment_item_type,
            posting_date,
            amount,
            currency,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentItemType {
    #[serde(rename = "partPaymentFinancialTransaction")]
    PartPaymentFinancialTransaction,
    #[serde(rename = "partPaymentCreditNote")]
    PartPaymentCreditNote,
    #[serde(rename = "partPaymentCashBox")]
    PartPaymentCashBox,
    #[serde(rename = "manualPayment")]
    ManualPayment,
    #[serde(rename = "cashDiscount")]
    CashDiscount,
    #[serde(rename = "dunningCosts")]
    DunningCosts,
    #[serde(rename = "currencyConversion")]
    CurrencyConversion,
}

impl Default for PaymentItemType {
    fn default() -> PaymentItemType {
        Self::PartPaymentFinancialTransaction
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "EUR")]
    Eur,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Eur
    }
}

