/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelatedVoucher {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "voucherNumber")]
    pub voucher_number: String,
    #[serde(rename = "voucherType")]
    pub voucher_type: String,
}

impl RelatedVoucher {
    pub fn new(id: uuid::Uuid, voucher_number: String, voucher_type: String) -> RelatedVoucher {
        RelatedVoucher {
            id,
            voucher_number,
            voucher_type,
        }
    }
}

