/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnitPrice {
    #[serde(rename = "currency")]
    pub currency: Currency,
    #[serde(rename = "netAmount")]
    pub net_amount: f64,
    #[serde(rename = "grossAmount")]
    pub gross_amount: f64,
    #[serde(rename = "taxRatePercentage")]
    pub tax_rate_percentage: f64,
}

impl UnitPrice {
    pub fn new(currency: Currency, net_amount: f64, gross_amount: f64, tax_rate_percentage: f64) -> UnitPrice {
        UnitPrice {
            currency,
            net_amount,
            gross_amount,
            tax_rate_percentage,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "EUR")]
    Eur,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Eur
    }
}

