/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoucherVoucherItemsInner {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    #[serde(rename = "taxAmount", skip_serializing_if = "Option::is_none")]
    pub tax_amount: Option<f64>,
    #[serde(rename = "taxRatePercent", skip_serializing_if = "Option::is_none")]
    pub tax_rate_percent: Option<f64>,
    #[serde(rename = "categoryId", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<uuid::Uuid>,
}

impl VoucherVoucherItemsInner {
    pub fn new() -> VoucherVoucherItemsInner {
        VoucherVoucherItemsInner {
            amount: None,
            tax_amount: None,
            tax_rate_percent: None,
            category_id: None,
        }
    }
}

