/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct XRechnung {
    #[serde(rename = "buyerReference", skip_serializing_if = "Option::is_none")]
    pub buyer_reference: Option<String>,
    #[serde(rename = "vendorNumberAtCustomer", skip_serializing_if = "Option::is_none")]
    pub vendor_number_at_customer: Option<String>,
}

impl XRechnung {
    pub fn new() -> XRechnung {
        XRechnung {
            buyer_reference: None,
            vendor_number_at_customer: None,
        }
    }
}

